/* AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
   Source of truth: scripts/sources.json -> scripts/build-media.mjs -> media-manifest.json */
window.WAXWIT_DATA = {
  "categories": [
    {
      "slug": "faces-that-influence",
      "name": "Faces that Influence"
    },
    {
      "slug": "fashion-brands",
      "name": "Brands with Main Character Energy"
    },
    {
      "slug": "interior-brands",
      "name": "Selling the Feel"
    },
    {
      "slug": "food-bakery",
      "name": "Brands you can almost taste"
    },
    {
      "slug": "hotel-restaurants",
      "name": "Design to be picked"
    },
    {
      "slug": "typography",
      "name": "Typography that talks"
    },
    {
      "slug": "promotional",
      "name": "Stories in motion"
    },
    {
      "slug": "logo-animation",
      "name": "Where brands begin"
    },
    {
      "slug": "built-for-paws",
      "name": "Built for paws"
    }
  ],
  "work": [
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Google reel",
      "video": "assets/videos/sapna-choudhary__google-reel.mp4",
      "poster": "assets/posters/sapna-choudhary__google-reel.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Gym reel",
      "video": "assets/videos/sapna-choudhary__gym-reel.mp4",
      "poster": "assets/posters/sapna-choudhary__gym-reel.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Meme reaction",
      "video": "assets/videos/sapna-choudhary__meme-reaction.mp4",
      "poster": "assets/posters/sapna-choudhary__meme-reaction.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Three things",
      "video": "assets/videos/sapna-choudhary__three-things.mp4",
      "poster": "assets/posters/sapna-choudhary__three-things.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "CEO life — Plasmapen & Cooljet",
      "video": "assets/videos/plasmapen__plasmapen-ceo-life.mp4",
      "poster": "assets/posters/plasmapen__plasmapen-ceo-life.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Product ad",
      "video": "assets/videos/plasmapen__plasmapen-ad-3.mp4",
      "poster": "assets/posters/plasmapen__plasmapen-ad-3.jpg",
      "orientation": "portrait",
      "w": 1080,
      "h": 1080
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Sweden launch",
      "video": "assets/videos/plasmapen__plasmapen-sweden.mp4",
      "poster": "assets/posters/plasmapen__plasmapen-sweden.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Brand ad",
      "video": "assets/videos/plasmapen__plasmapen-ad-1.mp4",
      "poster": "assets/posters/plasmapen__plasmapen-ad-1.jpg",
      "orientation": "portrait",
      "w": 1080,
      "h": 1080
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Bluweea II",
      "video": "assets/videos/fashion-brands__bluweea-2.mp4",
      "poster": "assets/posters/fashion-brands__bluweea-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Add to Cart",
      "video": "assets/videos/fashion-brands__add-to-cart.mp4",
      "poster": "assets/posters/fashion-brands__add-to-cart.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Beatnik",
      "video": "assets/videos/fashion-brands__beatnik.mp4",
      "poster": "assets/posters/fashion-brands__beatnik.jpg",
      "orientation": "portrait",
      "w": 360,
      "h": 640
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Snneha Jethwa II",
      "video": "assets/videos/fashion-brands__snneha-jethwa-2.mp4",
      "poster": "assets/posters/fashion-brands__snneha-jethwa-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Bluweea",
      "video": "assets/videos/fashion-brands__bluweea.mp4",
      "poster": "assets/posters/fashion-brands__bluweea.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Peppinos",
      "video": "assets/videos/fashion-brands__peppinos.mp4",
      "poster": "assets/posters/fashion-brands__peppinos.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Beatnik II",
      "video": "assets/videos/fashion-brands__beatnik-2.mp4",
      "poster": "assets/posters/fashion-brands__beatnik-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Snneha Jethwa",
      "video": "assets/videos/fashion-brands__snneha-jethwa.mp4",
      "poster": "assets/posters/fashion-brands__snneha-jethwa.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Hana Aesthetic",
      "video": "assets/videos/fashion-brands__hana-aesthetic-1.mp4",
      "poster": "assets/posters/fashion-brands__hana-aesthetic-1.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Hana Aesthetic",
      "video": "assets/videos/fashion-brands__hana-aesthetic-2.mp4",
      "poster": "assets/posters/fashion-brands__hana-aesthetic-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Hana Aesthetic",
      "video": "assets/videos/fashion-brands__hana-aesthetic-3.mp4",
      "poster": "assets/posters/fashion-brands__hana-aesthetic-3.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Acnepen",
      "video": "assets/videos/fashion-brands__acnepen-1.mp4",
      "poster": "assets/posters/fashion-brands__acnepen-1.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "fashion-brands",
      "categoryName": "Brands with Main Character Energy",
      "title": "Acnepen",
      "video": "assets/videos/fashion-brands__acnepen-2.mp4",
      "poster": "assets/posters/fashion-brands__acnepen-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Performance Marketing",
      "video": "assets/videos/personal-branding__pb-performance-marketing.mp4",
      "poster": "assets/posters/personal-branding__pb-performance-marketing.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Nutrition",
      "video": "assets/videos/personal-branding__pb-nutrition.mp4",
      "poster": "assets/posters/personal-branding__pb-nutrition.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Design",
      "video": "assets/videos/personal-branding__pb-design.mp4",
      "poster": "assets/posters/personal-branding__pb-design.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "faces-that-influence",
      "categoryName": "Faces that Influence",
      "title": "Nature",
      "video": "assets/videos/personal-branding__pb-nature.mp4",
      "poster": "assets/posters/personal-branding__pb-nature.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "interior-brands",
      "categoryName": "Selling the Feel",
      "title": "Rebuzz",
      "video": "assets/videos/interior-brands__rebuzz.mp4",
      "poster": "assets/posters/interior-brands__rebuzz.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "interior-brands",
      "categoryName": "Selling the Feel",
      "title": "Agashe",
      "video": "assets/videos/interior-brands__agashe.mp4",
      "poster": "assets/posters/interior-brands__agashe.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "interior-brands",
      "categoryName": "Selling the Feel",
      "title": "Arterior",
      "video": "assets/videos/interior-brands__arterior.mp4",
      "poster": "assets/posters/interior-brands__arterior.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "interior-brands",
      "categoryName": "Selling the Feel",
      "title": "Agashe II",
      "video": "assets/videos/interior-brands__agashe-2.mp4",
      "poster": "assets/posters/interior-brands__agashe-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Kokos",
      "video": "assets/videos/food-bakery__kokos.mp4",
      "poster": "assets/posters/food-bakery__kokos.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Xtraordinary",
      "video": "assets/videos/food-bakery__xtraordinary.mp4",
      "poster": "assets/posters/food-bakery__xtraordinary.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Tribbiani Pizzeria",
      "video": "assets/videos/food-bakery__tribbiani-1.mp4",
      "poster": "assets/posters/food-bakery__tribbiani-1.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Kokos II",
      "video": "assets/videos/food-bakery__kokos-2.mp4",
      "poster": "assets/posters/food-bakery__kokos-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Xtraordinary II",
      "video": "assets/videos/food-bakery__xtraordinary-2.mp4",
      "poster": "assets/posters/food-bakery__xtraordinary-2.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Tribbiani Pizzeria II",
      "video": "assets/videos/food-bakery__tribbiani-2.mp4",
      "poster": "assets/posters/food-bakery__tribbiani-2.jpg",
      "orientation": "portrait",
      "w": 360,
      "h": 640
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Xtraordinary",
      "video": "assets/videos/food-bakery__xtraordinary-3.mp4",
      "poster": "assets/posters/food-bakery__xtraordinary-3.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "food-bakery",
      "categoryName": "Brands you can almost taste",
      "title": "Xtraordinary",
      "video": "assets/videos/food-bakery__xtraordinary-4.mp4",
      "poster": "assets/posters/food-bakery__xtraordinary-4.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "hotel-restaurants",
      "categoryName": "Design to be picked",
      "title": "Halloween Reel",
      "video": "assets/videos/hotel-restaurants__halloween.mp4",
      "poster": "assets/posters/hotel-restaurants__halloween.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "hotel-restaurants",
      "categoryName": "Design to be picked",
      "title": "Hotel Harmony",
      "video": "assets/videos/hotel-restaurants__hotel-harmony.mp4",
      "poster": "assets/posters/hotel-restaurants__hotel-harmony.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "hotel-restaurants",
      "categoryName": "Design to be picked",
      "title": "Barrel",
      "video": "assets/videos/hotel-restaurants__barrel.mp4",
      "poster": "assets/posters/hotel-restaurants__barrel.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "hotel-restaurants",
      "categoryName": "Design to be picked",
      "title": "Park Inn by Radisson",
      "video": "assets/videos/hotel-restaurants__park-inn-radisson.mp4",
      "poster": "assets/posters/hotel-restaurants__park-inn-radisson.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "typography",
      "categoryName": "Typography that talks",
      "title": "Lead Physician",
      "video": "assets/videos/typography__lead-physician.mp4",
      "poster": "assets/posters/typography__lead-physician.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "typography",
      "categoryName": "Typography that talks",
      "title": "SN Capital",
      "video": "assets/videos/typography__sn-capital.mp4",
      "poster": "assets/posters/typography__sn-capital.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "typography",
      "categoryName": "Typography that talks",
      "title": "Nile Technologies",
      "video": "assets/videos/typography__nile-technologies.mp4",
      "poster": "assets/posters/typography__nile-technologies.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "typography",
      "categoryName": "Typography that talks",
      "title": "Care Exchange",
      "video": "assets/videos/typography__care-exchange.mp4",
      "poster": "assets/posters/typography__care-exchange.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "promotional",
      "categoryName": "Stories in motion",
      "title": "HBX Group",
      "video": "assets/videos/promotional__hbx-group.mp4",
      "poster": "assets/posters/promotional__hbx-group.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "promotional",
      "categoryName": "Stories in motion",
      "title": "Promo Video",
      "video": "assets/videos/promotional__promo-video.mp4",
      "poster": "assets/posters/promotional__promo-video.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "promotional",
      "categoryName": "Stories in motion",
      "title": "Long Form Promo",
      "video": "assets/videos/promotional__long-promo.mp4",
      "poster": "assets/posters/promotional__long-promo.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Logo Animation",
      "video": "assets/videos/logo-animation__logo-main.mp4",
      "poster": "assets/posters/logo-animation__logo-main.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Ink n Pixel",
      "video": "assets/videos/logo-animation__ink-n-pixel.mp4",
      "poster": "assets/posters/logo-animation__ink-n-pixel.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Logo Reveal",
      "video": "assets/videos/logo-animation__logo-reveal.mp4",
      "poster": "assets/posters/logo-animation__logo-reveal.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Final Render",
      "video": "assets/videos/logo-animation__final-render.mp4",
      "poster": "assets/posters/logo-animation__final-render.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Logo Animation II",
      "video": "assets/videos/logo-animation__logo-animation-2.mp4",
      "poster": "assets/posters/logo-animation__logo-animation-2.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Logo Reveal II",
      "video": "assets/videos/logo-animation__logo-new.mp4",
      "poster": "assets/posters/logo-animation__logo-new.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Tech Adisa",
      "video": "assets/videos/logo-animation__tech-adisa.mp4",
      "poster": "assets/posters/logo-animation__tech-adisa.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Tribbiani Logo",
      "video": "assets/videos/logo-animation__tribbiani-logo.mp4",
      "poster": "assets/posters/logo-animation__tribbiani-logo.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Barrel Logo",
      "video": "assets/videos/logo-animation__barrel-logo.mp4",
      "poster": "assets/posters/logo-animation__barrel-logo.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "logo-animation",
      "categoryName": "Where brands begin",
      "title": "Digital 3D Logo Reveal (4K)",
      "video": "assets/videos/logo-animation__3d-logo-reveal-4k.mp4",
      "poster": "assets/posters/logo-animation__3d-logo-reveal-4k.jpg",
      "orientation": "landscape",
      "w": 1280,
      "h": 720
    },
    {
      "category": "built-for-paws",
      "categoryName": "Built for paws",
      "title": "Woof Ministry",
      "video": "assets/videos/built-for-paws__woof-ministry-1.mp4",
      "poster": "assets/posters/built-for-paws__woof-ministry-1.jpg",
      "orientation": "portrait",
      "w": 720,
      "h": 1280
    }
  ]
};
