// Generate js/data.js from scripts/media-manifest.json (produced by build-media.mjs).
// Run after media finishes:  node scripts/gen-data.mjs
import fs from 'fs';
const ROOT = new URL('..', import.meta.url).pathname;
process.chdir(ROOT);

const manifest = JSON.parse(fs.readFileSync('scripts/media-manifest.json', 'utf8'));

// categories in first-seen order
const catOrder = [];
const seen = new Set();
for (const m of manifest) if (!seen.has(m.category)) { seen.add(m.category); catOrder.push({ slug: m.category, name: m.categoryName }); }

const work = manifest.map((m) => ({
  category: m.category,
  categoryName: m.categoryName,
  title: m.title,
  video: m.video,
  poster: m.poster,
  orientation: m.orientation,
  w: m.w,
  h: m.h,
}));

const out =
`/* AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
   Source of truth: scripts/sources.json -> scripts/build-media.mjs -> media-manifest.json */
window.WAXWIT_DATA = ${JSON.stringify({ categories: catOrder, work }, null, 2)};
`;
fs.writeFileSync('js/data.js', out);
console.log(`Wrote js/data.js: ${catOrder.length} categories, ${work.length} clips.`);
